<?php
/**
 * NewsCreateRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BITOP
 *
 * Bmstu Open IT Platform
 *
 * OpenAPI spec version: 1.0
 * Contact: i@spatecon.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * NewsCreateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description NewsCreateRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NewsCreateRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NewsCreateRequest"
     */
    public function testNewsCreateRequest()
    {
    }

    /**
     * Test attribute "action_type"
     */
    public function testPropertyActionType()
    {
    }

    /**
     * Test attribute "action_value"
     */
    public function testPropertyActionValue()
    {
    }

    /**
     * Test attribute "author"
     */
    public function testPropertyAuthor()
    {
    }

    /**
     * Test attribute "detail_description"
     */
    public function testPropertyDetailDescription()
    {
    }

    /**
     * Test attribute "detail_picture_url"
     */
    public function testPropertyDetailPictureUrl()
    {
    }

    /**
     * Test attribute "preview_description"
     */
    public function testPropertyPreviewDescription()
    {
    }

    /**
     * Test attribute "preview_picture_url"
     */
    public function testPropertyPreviewPictureUrl()
    {
    }

    /**
     * Test attribute "published"
     */
    public function testPropertyPublished()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }
}
