<?php
/**
 * NewsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BITOP
 *
 * Bmstu Open IT Platform
 *
 * OpenAPI spec version: 1.0
 * Contact: i@spatecon.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * NewsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NewsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for newsCreatePost
     *
     * Create news item.
     *
     */
    public function testNewsCreatePost()
    {
    }

    /**
     * Test case for newsDeleteUuidGet
     *
     * Delete news item.
     *
     */
    public function testNewsDeleteUuidGet()
    {
    }

    /**
     * Test case for newsListPost
     *
     * Get news list.
     *
     */
    public function testNewsListPost()
    {
    }

    /**
     * Test case for newsUpdateUuidPost
     *
     * Update news item.
     *
     */
    public function testNewsUpdateUuidPost()
    {
    }

    /**
     * Test case for newsUuidGet
     *
     * Get a news.
     *
     */
    public function testNewsUuidGet()
    {
    }
}
