<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BITOP
 *
 * Bmstu Open IT Platform
 *
 * OpenAPI spec version: 1.0
 * Contact: i@spatecon.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for userInfoByTicketTicketGet
     *
     * User info by Ticket.
     *
     */
    public function testUserInfoByTicketTicketGet()
    {
    }

    /**
     * Test case for userInfoByUuidUuidGet
     *
     * User info by UUID.
     *
     */
    public function testUserInfoByUuidUuidGet()
    {
    }

    /**
     * Test case for userLoginGet
     *
     * Redirect user to bmstu CAS auth form.
     *
     */
    public function testUserLoginGet()
    {
    }
}
